version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./sites:/public_html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet
  app:
    build:
      context: ./
      dockerfile: docker/app.docker
    container_name: resturant-demo
    volumes:
      - ./sites:/public_html
    networks:
      - appnet
  mysql:
    image: mysql:8
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=demo"
      - "TZ=Asia/Dhaka"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "33062:3306"
    networks:
      - appnet
  # redis:
  #   image: redis
  #   ports:
  #     - "63791:6379"
  #   networks:
  #     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
